export const cities = [
       {
              "slug": "london",
              "articles": [
                     {
                            "de": {
                                   "content": [
                                          "Die Stadt, in der Karl Marx mehr als die Hälfte seines Lebens verbrachte, war seit jeher die mit Abstand größte Stadt Englands bzw. Großbritanniens und seit 1841 mit knapp 1,7 Mio. Einwohnern vor Peking die größte Stadt der Welt. Erst 1925 wurde sie von New York von diesem Rang verdrängt. 1851 lebten hier rund 2 Mio. Menschen, 1881 3,9 Mio. Die Einwohnerzahl hat sich somit in den gut dreißig Jahren, die Karl Marx in London lebte, verdoppelt. Die ganze Zeit über herrschte dort Königin Victoria über ein Drittel der Weltbevölkerung.",
                                          "Durch mehrere Wahlrechtsänderungen erhielten immer mehr Briten Teilhabe am (von den Parteien der Konservativen und der Liberalen bestimmten) politischen Leben; Ende des 19. Jahrhunderts waren rund 60 % der männlichen Bevölkerung wahlberechtigt. London zog Einwanderer aus den Kolonien und aus Europa an. Neben enormer Armut kennzeichnete das London des 19. Jahrhunderts auch ungewöhnlicher technischer Fortschritt, die britische Hauptstadt war in vielerlei Hinsicht bahnbrechend (Eisenbahn, Weltausstellung, U-Bahn, Straßenbeleuchtung). Handel und Gewerbe – insbesondere der Bau-, der Textil- und der Nahrungsmittelsektor – florierten, obwohl es kaum große Industrieunternehmen gab. Zudem war London ein überaus bedeutender Druck-, Verlags- und Zeitungsstandort. Pressefreiheit herrschte im Vereinigten Königreich bereits seit 1695. Die Gesamtauflage der fast 80 Zeitungen belief sich 1837 auf 6 Mio. im Jahr, 1850 bereits auf mehr als 31 Mio. In der City gab es eine Vielzahl großer Geschäfte und Banken; London war der wichtigste Finanzplatz der Welt.",
                                          "Der Aufschwung hatte einen massiven Anstieg der Grundstückspreise zur Folge. Aufgrund der guten Verkehrsanbindung siedelten immer mehr wohlhabende Londoner in das Umland über, die dicht bebaute Innenstadt blieb den Armen überlassen. Das ungebremste Bevölkerungswachstum führte seit der Jahrhundertmitte zu einer starken Umweltbelastung. Da die Abwässer direkt in die Themse geleitet wurden und der Fluss zudem der Trinkwasserversorgung diente, brachen regelmäßig Choleraepidemien aus, allein im Jahr 1854 starben daran über 10.000 Menschen. Im heißen Sommer 1858 führten die desaströsen Abwasserverhältnisse zum „Great Stink“; in der Folgezeit erhielt London jedoch 1859–1875 ein überaus modernes, 1.750 km langes Kanalisations- und Abwassersystem."
                                   ],
                                   "title": "London – Globalisierung, Fortschritt und Armut (1849–1883)"
                            },
                            "en": {
                                   "content": [
                                          "The city in which Karl Marx was to spend over half of his lifetime had long been the largest metropolis in England and Great Britain and since 1841 had surpassed Peking as the largest city in the world, with almost 1.7 million inhabitants. It only lost this status to New York in 1925. By 1851, around 2 million people lived there, in 1881 3.9 million. The population thus doubled in the thirty years that Karl Marx lived in London. Throughout the entire time, Queen Victoria reigned over one-third of the global population.",
                                          "Various changes to voting laws meant that an increasing percentage of the British population was able to participate in politics (dominated by the Conservative and Liberal parties); at the close of the 19th century, around 60 percent of the male population had the right to vote. London attracted migrants from the colonies and Europe. In addition to extreme poverty, 19th-century London was defined by remarkably rapid technological progress; the British capital was a pioneer in many areas (railway, world’s fair, the underground, street lighting). Crafts and commerce – especially in the construction, textile, and food industries – flourished even though there were few large industrial companies. London was also a significant centre for printing, publishing houses, and newspapers. Press freedom had been guaranteed in the United Kingdom since 1695. Almost 80 newspapers achieved a circulation of 6 million per year in 1837; by 1850 the number had grown to over 31 million. There were numerous large businesses and banks in the city. London was the most important financial centre worldwide.",
                                          "The boom caused property prices to rise considerably. On account of the good transport connections, ever more wealthy Londoners settled in the surrounding suburbs, leaving the densely built-up inner city to the poor. The unrelenting population growth resulted in serious environmental degradation that prevailed from the mid-century onwards. As wastewater was pumped straight back into the River Thames, which was also used for drinking water, cholera epidemics were frequent. More than 10,000 people died from the disease in 1854 alone. In the hot summer of 1858, the disastrous sewage system caused what was dubbed the ‘Great Stink’; afterwards, a thoroughly modern, 1,750-kilometer-long sewer and wastewater system was built throughout the city from 1859 to 1875."
                                   ],
                                   "title": "London – Globalization, Progress, and Poverty  (1849–1883)"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Im Schatten des Aufschwungs von Handel und Gewerbe, der einer kleinen Oberschicht zu riesigem Vermögen verhalf, lebten Ende des 19. Jahrhunderts über 30 % der Londoner in Armut, über 11 % am Rande des Existenzminimums. Die Wohnverhältnisse in den oft in Back-to-back-Bauweise errichteten Massenquartieren waren desaströs. Dass sich acht Personen einen Raum teilen mussten, war keine Ausnahme, und durch große Bauprojekte sowie die Eisenbahnanlagen wurde noch mehr Wohnraum vernichtet. Besonders betroffen hiervon waren die irischen Einwanderer, die nicht selten zu zwanzig in einem Zimmer hausten. Ende des 19. Jahrhunderts lebten in London 30 % der Bevölkerung in überbelegten („overcrowded“) Wohnungen, in den ärmeren Stadtteilen sogar über 40 %.",
                                          "Da zudem zumindest während der ersten Hälfte des 19. Jahrhunderts die hygienischen Verhältnisse, die medizinische Versorgung und die Ernährung mangelhaft waren, lag 1841 die durchschnittliche Lebenserwartung der Londoner bei nur 37 Jahren, bei den „labourers, mechanics, and servants“ sogar nur bei 15 Jahren. In dicht besiedelten Stadtteilen wie Shoreditch, Whitechapel und Bermondsey war sie nur halb so hoch wie in den Wohngegenden der Mittelschicht. Gegen Ende des Jahrhunderts besserte sich die Ernährungslage, die Lebensmittelpreise fielen zwischen 1877 und 1889 um rund 30 %. Zudem besaß London nun ein sehr fortschrittliches Abwassersystem.",
                                          "1834 war ein neues Armengesetz (New Poor Law) in Kraft getreten – vor allem um die von den Wohlhabenderen erhobene Armensteuer senken zu können. Ziel war eine kosteneffizientere Armenfürsorge: Fortan wurde allen Arbeitsfähigen die individuelle Unterstützung entzogen, stattdessen wies man sie in Workhouses (Arbeitshäuser) ein, die eher Gefängnissen glichen. Die Arbeitsbedingungen dort waren sehr hart, die Ernährungssituation der Insassen bewusst schlecht, um keinen Anreiz zu schaffen, ein Leben im Workhouse den prekären Umständen in Freiheit vorzuziehen („less eligibility“). Das New Poor Law wurde in der Folge – auch aufgrund von Kritik an den Umständen und Skandalen – mehrfach, aber nicht substanziell überarbeitet.",
                                          "Die Situation der Armen beschrieb Friedrich Engels in seinem grundlegenden Werk Die Lage der arbeitenden Klasse in England (1845). Literarisch hatte der Schriftsteller Charles Dickens eine breite Öffentlichkeit damit konfrontiert (etwa 1839 mit Oliver Twist). Henry Mayhew, einer der Gründer des Satiremagazins Punch, fasste seine zahlreichen Artikel 1851 in drei Bänden mit dem Titel London Labour and the London Poor zusammen. Großen Erfolg hatten ab 1869 auch die Darstellungen von Armut und Ungerechtigkeit des Malers und Illustrators Luke Fildes."
                                   ],
                                   "title": "Armut in London"
                            },
                            "en": {
                                   "content": [
                                          "The shadow side to the boom in crafts and commerce that allowed a small proportion of the upper class to accumulate enormous wealth was that by the close of the 19th century, more than 30 percent of Londoners lived in poverty and over 11 percent at subsistence levels. Living conditions in the typical back-to-back terraced housing of the workers’ quarters were dire. Eight people to a room was no exception and large building projects and the construction of the railway destroyed even more residential areas. Irish immigrants were particularly badly affected, often living twenty to a room. At the end of the 19th century, 30 percent of London’s inhabitants lived in overcrowded dwellings, rising to over 40 percent in the poorest city districts.",
                                          "Further compounded by poor hygiene, lack of medical care, and malnutrition, at least in the first half of the century, the average life expectancy of a London resident was just 37 years in 1841, that of ‘labourers, mechanics, and servants’ just 15 years. In densely populated areas like Shoreditch, Whitechapel, and Bermondsey, it was just half of the average in middle-class districts. Food shortages became less acute towards the end of the century and prices fell by about 30 percent between 1877 and 1889. In addition, London finally gained a modern sewer system.",
                                          "The New Poor Law came into force in 1834 – primarily to reduce the poor tax levied on the rich. The aim was to find a more efficient way to care for the poor. Those who were capable of working were no longer entitled to individual support and instead were sent to workhouses, which were more like prisons. The working conditions were extremely hard, and occupants were deliberately given little food to discourage people from choosing life in the workhouse over the more precarious conditions of a life in freedom (‘less eligibility’). The New Poor Law was subsequently amended many times – in part due to criticism of the conditions and scandals – but never substantially revised.",
                                          "The situation of the poor was described by Friedrich Engels in his seminal work Die Lage der arbeitenden Klasse in England (The Condition of the Working Class in England, 1845). In literature, the author Charles Dickens had presented the realities of life in poverty to a wide audience (e.g., in Oliver Twist in 1839). Henry Mayhew, co-founder of the satire magazine Punch, compiled his many articles from 1851 in three volumes titled London Labour and the London Poor. The scenes of poverty and injustice by painter and illustrator Luke Fildes enjoyed great success from 1869."
                                   ],
                                   "title": "Poverty in London"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Während große Teile der Londoner in erbärmlichen Verhältnissen lebten, standen dem Adel und dem Großbürgertum eine Fülle an kulturellen Einrichtungen und Stätten zur Freizeitgestaltung zur Verfügung. Das reichte von den berühmten viktorianischen Clubs über Parks, den Zoo und diverse Sportstätten bis hin zum Wachsfigurenkabinett und großen Panoramen. Seit 1753 gab es das British Museum mit seiner angeschlossenen Bibliothek, in der Karl Marx seine Studien betrieb. Weitere Museen folgten, so 1824 die National Gallery, 1852 das Victoria and Albert Museum und 1857 das Science Museum. Das bedeutendste Theater war das Covent Garden Theatre, jedoch brach der Theatres Act von 1843 dessen Monopolstellung und erlaubte es, auch ohne Lizenz ein Theater zu betreiben. In der Folgezeit machten zahlreiche Bühnen und Musikhallen der Traditionsspielstätte Konkurrenz.",
                                          "1836 wurde die University of London gegründet, seit 1878 durften hier auch Frauen ein Examen ablegen. In den 1860er-Jahren gab es in London 860 öffentliche und rund 1.700 private Schulen, allerdings viel zu wenige Mädchenschulen. Schulpflicht bestand seit 1870.",
                                          "Die „Great Exhibition“ von 1851 war die erste Weltausstellung überhaupt, sie zog 19.000 Aussteller und rund 6 Mio. Besucher an und galt als Aushängeschild Großbritanniens als führender Industrienation der Welt. Hierzu hatte man den Crystal Palace errichtet, eine 564 m lange und 138 m breite Eisen-Glas-Konstruktion mit 38 m hoher Kuppel. Auch die 5. Weltausstellung 1862 fand in London statt. Mit den erwirtschafteten Überschüssen wurden das Victoria and Albert Museum, das Science Museum und der Neubau des British Museum (1880) finanziert. Im Jahr der ersten Weltausstellung wurde in London auch das foucaultsche Pendel gezeigt."
                                   ],
                                   "title": "London als Kulturmetropole"
                            },
                            "en": {
                                   "content": [
                                          "While large numbers of Londoners lived in appalling conditions, the nobility and upper classes had a wealth of recreational pursuits to choose from with numerous cultural institutions and venues, ranging from the famed Victorian clubs, parks, the zoo, and various sports facilities to the waxworks museum and large-scale panoramas. The British Museum had opened its doors in 1753 along with its library where Karl Marx often studied. Other museums followed, such as the National Gallery in 1824, the Victoria and Albert Museum in 1852 and the Science Museum in 1857. The most important theatre was Covent Garden Theatre, although its monopoly was broken by the Theatre Act of 1843, which allowed theatres to be operated without a licence. This led to increased competition for the traditional venues from a plethora of new theatres and music halls.",
                                          "The University of London was founded in 1836 and permitted women to sit exams there from 1878. In the 1860s, London had 860 public and about 1,700 private schools, but there was still a serious lack of schools for girls. School attendance was made compulsory in 1870.",
                                          "The Great Exhibition of 1851 was the first ever world’s fair and attracted 19,000 exhibitors and about 6 million visitors. It served to promote Great Britain as the leading industrial nation in the world. The Crystal Palace was erected for the event, an iron and glass construction, 564 metres long and 138 metres wide with a 38-metre-high dome. The fifth world’s fair also took place in London in 1862. The profits were used to fund the Victoria and Albert Museum, the Science Museum and the new building for the British Museum (1880). The Foucault Pendulum was exhibited in London in the year of the first world’s fair too."
                                   ],
                                   "title": "London as a Cultural Metropolis"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Seit 1829 fuhren in London Omnibusse, und bereits 1836 gab es eine Eisenbahn von London Bridge nach Greenwich. Als Karl Marx nach London übersiedelte, standen dort bereits fünf Bahnhöfe, darunter seit 1837 die Euston Station, die die Hauptstadt mit Birmingham, Manchester, Liverpool und Glasgow verband. Drei weitere sollten hinzukommen: Die King’s Cross Station(1852) als Ausgangspunkt der Strecke nach Ostschottland, die benachbarte St Pancras Station, die seit 1868 die östlichen Midlands und Yorkshire an die Hauptstadt anband, und die Victoria Station, von wo aus Züge seit 1860 in die südlichen Vororte und den Südosten Englands führten. Seit 1861 verkehrte die erste Straßenbahn der Welt, 1863 nahm die weltweit erste – zunächst mit Dampflokomotiven betriebene – Untergrundbahn den Betrieb auf. Während des 19. Jahrhunderts wurden die Dockanlagen des Welthafens London mit ihren zahlreichen Speicherhäusern kontinuierlich ausgebaut."
                                   ],
                                   "title": "London als Verkehrsmetropole"
                            },
                            "en": {
                                   "content": [
                                          "Busses were first introduced to London in 1829 and by 1836 there was a railway line from London Bridge to Greenwich. When Karl Marx moved to London, the city had five train stations, including Euston Station from 1837, which connected the capital city with Birmingham, Manchester, Liverpool, and Glasgow. Three further stations soon followed: King’s Cross Station (1852), the point of departure for trains to East Scotland, the neighbouring St. Pancras Station, which linked the East Midlands and Yorkshire with the capital from 1868, and Victoria Station, which served the southern suburbs and the southeast of England from 1860. The first tram worldwide went into operation in 1861 and 1863 saw the inauguration of the first ever underground train – initially operated by steam locomotives. During the 19th century, the docklands of the international Port of London with its numerous warehouses were continually expanded."
                                   ],
                                   "title": "London as a Transport Hub"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Nach der Ausweisung aus Brüssel und Paris und der Niederlage der Revolution blieb Karl Marx nur noch Großbritannien als Demokratie zum Leben im Exil. Im Juli 1849 ging er daher nach London, seine hochschwangere Frau Jenny folgte ihm zusammen mit den Kindern Jenny(chen), Laura und Edgar („Musch“) sowie Helene Demuth wenige Wochen später.",
                                          "Wie andere Flüchtlinge vom Kontinent dachten sie an einen nur vorübergehenden Aufenthalt im Exil. Während mehrerer Jahre waren Leben und Aktivitäten geprägt von dem Glauben an eine neue Revolution. Heftige Auseinandersetzungen über die jeweils richtige politische Taktik und persönliches Gezänk waren unter den Bedingungen der Emigration an der Tagesordnung.",
                                          "Die Familie zog in London mehrfach um. Zunächst wohnte sie in Pensionen, darunter dem German House am Leicester Square, wo viele deutsche Flüchtlinge vorübergehend eine billige Unterkunft fanden. Es folgten mehrere Jahre unter schwierigen Umständen in der Dean Street in Soho. 1849 kam der Sohn Heinrich Guido „(Föxchen“), 1851 die Tochter Franziska zur Welt, die aber beide nicht älter als ein Jahr wurden. Ein 1851 geborener unehelicher Sohn der Haushälterin Helene Demuth, dessen Vater höchstwahrscheinlich Karl Marx war, wurde in eine Pflegefamilie gegeben. Die ersten Jahre in London waren für die Familie sehr bedrückend, zeitweise lebte sie zu siebt in einer Zweizimmerwohnung (Karl und Jenny Marx, die Kinder Jenny, Laura, Edgar und Franziska, Helene Demuth und eine Amme). Karl Marx konnte aus der Enge der Wohnung in die nahe gelegene British Library fliehen. 1850 wurde die Familie vom Vermieter auf die Straße gesetzt. Zu den Krankheiten, die Karl Marx zeitlebens begleiteten, kamen ständige Geldsorgen. Er war immer auf Beihilfen von Freunden, insbesondere von Friedrich Engels, angewiesen. Meist war es Jenny, die unzählige Bittbriefe schrieb. Auch als sich später die Situation besserte, blieb es bei ständigen Finanznöten. Dabei handelte es sich jedoch nicht mehr um bittere Armut. Ursache war vielmehr auch das Bestreben, nach außen den Schein bürgerlich-viktorianischer Respektabilität zu wahren. Hinzu kam das Unvermögen von Jenny und Karl Marx, haushälterisch mit Geld umzugehen.",
                                          "1855 beerbte Jenny ihre schottische Großmutter. Dies ermöglichte es der Familie, im Jahr darauf in ein geräumiges Haus in Grafton Terrace zu ziehen, gelegen in einem ländlich geprägten Neubauviertel nahe des großen Parks Hampstead Heath. Dort wohnte die Familie Marx, bis sie 1864 in die nahe gelegene Maitland Park Road übersiedelte. Zwei Erbschaften verbesserten im selben Jahr die Lage der Familie für kurze Zeit erheblich: Der Freund Wilhelm Wolff hinterließ Marx ein nicht unbeträchtliches Vermögen und nach dem Tod der Mutter erhielt Marx die langersehnte Erbschaft. Verbunden damit war ein Wechsel im Lebensstil: Die häuslichen Verhältnisse wurden großzügiger. Die Kinder hatten eigene Zimmer, man hielt Haustiere und hatte ein zweites Hausmädchen. Die Mädchen gingen auf eine Privatschule für höhere Töchter, erhielten Unterricht in Französisch und Klavierspiel. Bälle wurden veranstaltet, Reisen an die See und sonntägliche Ausflüge in die Umgebung unternommen.",
                                          "Abgesehen von den Erbschaften und der Unterstützung durch Engels finanzierte Karl Marx sich und seine Familie durch seine journalistische Tätigkeit. Jenny diente ihm als Sekretärin, Helene Demuth führte den Haushalt. 1867 erschien in Hamburg der 1. Band von Das Kapital. Aus Marx‘ Manuskripten stellte Engels nach dessen Tod den 2. und 3. Band zusammen und gab diese 1885 bzw. 1894 ebenfalls in Hamburg heraus. 1884 erschien die erste englische Übersetzung.",
                                          "Insgesamt verlief das Leben von Karl und Jenny Marx seit den 1870er-Jahren äußerlich ruhiger. Friedrich Engels hatte sich aus dem Geschäft in Manchester zurückgezogen und war 1870 in die unmittelbare Nachbarschaft in London gezogen. Er konnte nun der Familie Marx eine erhebliche jährliche Leibrente aussetzen, die freilich nie ausreichte. An die Stelle finanzieller Sorgen traten verstärkt gesundheitliche Probleme, die Karl und Jenny Marx durch Kuren zu lindern suchten.",
                                          "Schwere Schicksalsschläge trafen vor allem Jenny Marx hart. Vier von sieben zwischen 1844 und 1857 geborenen Kindern starben noch im Kindesalter. Besonders schmerzlich war für die Eltern der Tod ihres Sohnes Edgar, der 1855 im Alter von acht Jahren starb. Seit 1860 war Jenny von den Folgen einer Pockenerkrankung gezeichnet. Trotz dieser persönlichen Schicksalsschläge übertrug sie weiterhin die Manuskripte von Karl Marx in eine leserliche Handschrift und verfasste auch eigene kleinere literarische Arbeiten (Theaterkritiken). Jahrelang quälte Jenny ihr Krebsleiden. Sie starb am 2. Dezember 1881 in London. Karl Marx überlebte sie nur um fünfzehn Monate.",
                                          "Während der gesamten Londoner Zeit führte Helene Demuth den Haushalt der Familie Marx. 1857 wurde auch ihre Schwester Marianne als Haushaltshilfe eingestellt, diese starb 1862. Nach Karl Marx‘ Tod 1883 zog „Lenchen“ zu Friedrich Engels und wurde dessen Haushälterin bis zu ihrem Tod 1890.",
                                          "Die drei überlebenden Kinder von Jenny und Karl Marx waren die Töchter Jenny (1844–1883), Laura (1845–1911) und Eleanor (1855–1898). Wie die Eltern waren sie überdurchschnittlich begabt und außerordentlich gebildet. Sie hatten eigene Interessen und Lebensziele, blieben jedoch im Bann von Karl Marx. Zuerst waren sie Helferinnen des Vaters, dann ihrer Ehemänner. Ihre Leben endeten tragisch.",
                                          "Jenny(chen), die älteste Tochter, wurde in Paris geboren und war dem Vater äußerlich sehr ähnlich. Sie arbeitete eine Weile als Hauslehrerin und heiratete 1872 den französischen Sozialisten Charles Longuet (1839–1903). Dieser war Journalist, Delegierter auf Kongressen der Ersten Internationale, dem ersten länderübergreifenden Zusammenschluss von Arbeiterparteien, und aktiv an der Pariser Kommune, dem blutig niedergeschlagenen Aufstand während der Belagerung von 1871, beteiligt. Er floh nach England und kehrte nach der Amnestie für die Kommunarden mit Frau und Kindern nach Frankreich zurück. Aus dieser Verbindung stammen die in Frankreich lebenden Nachfahren von Karl Marx. Die Familie ließ sich in Argenteuil bei Paris nieder. Dort starb Jenny Longuet 1883 kurz nach der Geburt ihres sechsten Kindes und vor dem Tod ihres Vaters im Alter von 39 Jahren an Krebs.",
                                          "Auch die in Brüssel geborene Tochter Laura heiratete einen französischen Sozialisten, den aus Kuba stammenden Arzt Paul Lafargue (1842–1911). Zusammen übersetzten sie das Manifest der Kommunistischen Partei ins Französische. Lafargue war ebenfalls in der Internationale aktiv und an der Kommune von 1871 beteiligt. Nach dem Scheitern des Aufstands ging die Familie zunächst ins spanische, dann ins englische Exil, wo sie von Friedrich Engels finanziell unterstützt wurde. Nach ihrer Rückkehr nach Frankreich 1880 engagierten sich beide in der französischen Arbeiterbewegung. 1911 begingen sie zusammen Selbstmord. An dem Trauerzug zum Friedhof Père Lachaise nahmen 15.000 Menschen teil, Lenin war einer der Grabredner. Die beiden Söhne und die Tochter waren bereits als Kleinkinder gestorben.",
                                          "Eleanor Marx, genannt Tussy: Die jüngste Marx-Tochter galt als politisch besonders begabt und engagiert. Ihre Sympathie galt den Iren und deren Freiheitskampf gegen England. Auch sie wollte einen französischen Sozialisten heiraten, den Journalisten und Kommunarden Prosper-Olivier Lissagaray (1838–1901). Dieser veröffentlichte 1876 in Brüssel sein Hauptwerk L’Histoire de la Commune, um der Geschichtsschreibung der Sieger den Standpunkt der Kommunarden entgegenzusetzen. Karl Marx lehnte die Verbindung seiner Tochter mit Lissagaray jedoch ab und nach fast zehnjähriger heimlicher Verlobung fügte sich Eleanor. Sie begleitete den Vater in seinen späten Jahren auf zahlreichen Kurreisen und fungierte schließlich wie die Mutter als seine Sekretärin. Bis zum Tod von Engels (1895) half sie diesem bei der Sichtung des väterlichen Nachlasses. Seit 1884 lebte sie mit dem englischen Arzt, Schriftsteller und Sozialisten Edward Aveling (1851–1898) zusammen, mit dem sie ihre Theaterbegeisterung und das Engagement für die englische Arbeiterbewegung verband. Sie war an der englischen Übersetzung von Marx‘ Das Kapital (1884) beteiligt und übersetzte Lissagarays Geschichte der Kommune 1886 ins Englische. Die Beziehung mit Aveling verlief jedoch sehr unglücklich, 1898 setzte Eleanor Marx ihrem Leben selbst ein Ende."
                                   ],
                                   "title": "Karl Marx in London"
                            },
                            "en": {
                                   "content": [
                                          "After his expulsion from Brussels and Paris and the defeat of the 1848 revolution, Great Britain was the only democracy left where Karl Marx could hope to start life again as an exile. In July 1849, he moved to London and his heavily pregnant wife Jenny followed him a few weeks later with the children Jennychen, Laura, and Edgar (‘Musch’) as well as Helene Demuth, the housekeeper.",
                                          "Like other political refugees from the continent, their exile was only intended to be temporary. For many years, life and activities were dictated by their belief in a new revolution. Bitter altercations over the right political strategy to employ and personal squabbles were the order of the day under the conditions in exile.",
                                          "The family moved many times within London. They first lived in boarding houses, including the German House on Leicester Square, where many German immigrants found cheap temporary accommodation. Then came several difficult years in Dean Street in Soho. In 1849, their son Heinrich Guido (‘Föxchen’) was born and in 1851, their daughter Franziska, but neither survived beyond the age of one. An illegitimate son born to their housekeeper Helene Demuth in 1851, whose father was most likely Karl Marx, was given to a foster family. The first years in London were very hard, at times seven of them lived in a two-room apartment (Karl and Jenny Marx, the children Jenny, Laura, Edgar, and Franziska, Helene Demuth and a nurse). Karl Marx was able to escape the cramped conditions by fleeing to the nearby British Library. In 1850, the family was evicted by the landlord. In addition to the illnesses that accompanied Karl Marx his entire life, money was another constant worry. He was always reliant on help from friends, especially Friedrich Engels. It was usually Jenny who wrote the countless begging letters. Even when the family finances later improved, money was always tight. By that time, however, they no longer faced extreme poverty but were overstretched financially by the attempt to maintain a semblance of middle-class, Victorian respectability. Their situation was further exacerbated by the fact that neither Jenny nor Karl Marx was capable of managing their household budget properly.",
                                          "In 1855, Jenny inherited from her Scottish grandmother, which allowed the family to move to a spacious house in Grafton Terrace the following year. It was situated in a new developing district that was still quite rural, near the large park Hampstead Heath. The family lived there until they moved to the neighbouring Maitland Park Road in 1864. Two further inheritances that same year drastically improved the family’s situation for a time: their friend Wilhelm Wolff left Marx quite a considerable sum, and on the death of his mother, Marx received the long-awaited inheritance from his father’s estate. Their lifestyle changed accordingly: they expanded their living quarters, the children each getting a room of their own, acquired pets and employed a second servant. The girls attended a private school for daughters of the upper classes and learned French and piano. The family hosted balls, went on excursions to the coast and Sunday outings to the surrounding countryside.",
                                          "Aside from these inheritances and Engels’ ongoing support, Karl Marx provided for himself and his family through his journalism. Jenny worked as his secretary, while Helene Demuth managed the household affairs. In 1867, the first volume of Das Kapital was published in Hamburg. Engels compiled the second and third volumes from Marx’s manuscripts after his death and published them, again in Hamburg, in 1885 and 1894 respectively. The first English translation was published Iin 1884.",
                                          "Overall, Karl and Jenny Marx led a quieter life, at least outwardly, from the 1870s on. Friedrich Engels retired from the business in Manchester and moved nearby to them in London in 1870. From that time on, he was able to pay the Marx family a generous annuity, although it never seemed to suffice. Health problems increasingly superseded financial concerns, which Karl and Jenny Marx attempted to treat at Europe’s mineral baths and spas.",
                                          "Jenny Marx in particular endured several tragedies in her life. Four of seven children born between 1844 and 1857 died at a young age. Especially painful for the couple was the death of their son Edgar, who was just eight years old when he died in 1855. From 1860, Jenny was further marked by a bout of smallpox. Despite these personal setbacks, she continued to rewrite Karl Marx’s manuscripts in legible handwriting and wrote her own shorter literary works (mostly theatre reviews). She suffered from cancer for several years and died on 2 December 1881 in London. Karl Marx only survived her by fifteen months.",
                                          "During their whole time in London, the household of the Marx family was managed by Helene Demuth. In 1857, her sister Marianne was employed to assist her; she died in 1862. After Karl Marx’s death in 1883, ‘Lenchen’ moved to Friedrich Engels and worked for him until her death in 1890.",
                                          "The three surviving children of Jenny and Karl Marx were their daughters Jenny (1844–1883), Laura (1845–1911), and Eleanor (1855–1898). Like their parents they had above-average talents and were extremely well educated. They had their own interests and ambitions but remained in the thrall of their father Karl Marx. At first they worked as his assistants and later for their husbands. Their lives all ended tragically.",
                                          "Jenny(chen), the eldest daughter, was born in Paris and looked very like her father. She worked for a while as a governess and in 1872 married the French socialist Charles Longuet (1839–1903). He was a journalist, delegate at congresses of the First International, the first cross-border union of workers’ parties, and was active in the Paris Commune, the uprising that was viciously suppressed during the siege of 1871. He fled to England, later returning to France with his wife and children when the Communards were granted amnesty. From this marriage stem the living descendants of Karl Marx in France. The couple settled in Argenteuil near Paris. Jenny Longuet died from cancer there in 1883 at the age of 39 years, just after the birth of her sixth child and before her father’s death.",
                                          "Karl and Jenny Marx’s daughter Laura, born in Brussels, also married a French socialist, the Cuban doctor Paul Lafargue (1842–1911). Together, they translated the Communist Manifesto into French. Lafargue was also involved in the First International and was part of the Paris Commune of 1871. After the defeat of the revolution, the family went into exile in Spain and then moved to England, where they were financially supported by Friedrich Engels. After their return to France in 1880, they both participated in the French workers’ movement. In 1911, they committed suicide together. The funeral cortege to the Père Lachaise cemetery comprised 15,000 people, and Lenin spoke at their graveside. Their two sons and one daughter had died as small children.",
                                          "Eleanor Marx (nicknamed ‘Tussy’), the youngest of the Marx sisters, was considered to have a particular talent for politics and was very active politically. She supported the Irish and their fight for independence from England. She too wanted to marry a French socialist, the journalist and Communard Prosper-Olivier Lissagaray (1838–1901). He published his major work L’Histoire de la Commune, 1876, in Brussels in order to oppose the victors’ account of history with the perspective of the Commune. Karl Marx refused to allow his daughter to marry Lissagaray, however, and after an almost ten-year secret engagement, Eleanor gave in. She accompanied her father in his later years to numerous spas and ultimately worked as his secretary like her mother before her. Until Engels died (in 1895), she helped him to manage her father’s estate. From 1884, she lived with the English doctor, writer, and socialist Edward Aveling (1851–1898), with whom she shared a love of the theatre and her commitment to the English workers’ movement. She co-translated Marx’s Das Kapital (1884) and translated Lissagaray’s history of the Commune into English in 1886. Her relationship with Aveling was unhappy, however, and in 1898 Eleanor Marx took her own life."
                                   ],
                                   "title": "Karl Marx in London"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Die Kindersterblichkeit stellte (nicht nur) in London während des gesamten 19. Jahrhunderts ein großes Problem dar. Die Ursachen hierfür waren vielfältig: mangelnde Sanitäreinrichtungen, unzureichende medizinische Versorgung, Choleraepidemien und andere Seuchen, beengte Wohnverhältnisse, Mangelernährung. Zu Beginn des 19. Jahrhunderts starb mehr als ein Drittel der Kinder vor Vollendung des fünften Lebensjahres. Auch noch in den 1890er-Jahrenvollendeten trotz erzielter Fortschritte in den wohlhabendsten Vierteln Londons über 11 %, in den ärmsten sogar rund 18 % nicht ihr erstes Lebensjahr. Von den sieben Kindern der Familie Marx erreichten nur drei das Erwachsenenalter, und alle drei Kinder ihrer Tochter Laura starben als Säuglinge oder Kleinkinder. Immerhin waren Ernährungszustand und Gesundheit der Kinder Ende des 19. Jahrhunderts erheblich besser als hundert Jahre zuvor."
                                   ],
                                   "title": "Kindersterblichkeit"
                            },
                            "en": {
                                   "content": [
                                          "Child mortality in London (and elsewhere) was a major problem throughout the entire 19th century. The reasons behind it were many: poor sanitation, insufficient medical care, cholera epidemics and other plagues, overcrowded living space, malnutrition. In the early 19th century, over a third of children died before the age of five. Even in the 1890s, despite the progress that had been achieved, over 11 percent in the wealthiest districts of London and about 18 percent in the poorest did not survive their first year. Of the seven children born to the Marx family only three survived into adulthood and all three of their daughter Laura’s children died as babies or toddlers. Still, children’s diet and health were considerably better by the end of the 19th century than they had been one hundred years earlier."
                                   ],
                                   "title": "Child Mortality"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Bereits zu Beginn des 19. Jahrhunderts war London eine kosmopolitische Stadt, die mit dem Aufschwung von Handel und Gewerbe Migranten aus dem Umland, ganz England, dem Commonwealth und dem europäischen Ausland anzog. Insbesondere ließen sich hier nach der Hungersnot 1845–1849 zahlreiche katholische Iren nieder, die schließlich 20 % der Stadtbevölkerung ausmachten, fast ausnahmslos in übervölkerten Slums lebten und auch wegen ihrer Religion ausgegrenzt wurden. Aufgrund wirtschaftlicher Not oder politischer Verfolgung flohen auch viele Menschen aus den deutschen Ländern und Frankreich, aber auch aus Italien, Spanien, Polen u. a. nach London. Um 1850 war immerhin 1 % der Londoner im Ausland geboren, fünfzig Jahre später war ihr Anteil auf 3 % angewachsen.",
                                          "Die Zahl der Juden stieg während des 19. Jahrhunderts kontinuierlich an. Viele waren im Bankwesen, im Groß- und Einzelhandel oder als Unternehmer im Textilbereich tätig. Im Schnitt waren sie deutlich wohlhabender als der Durchschnitt der Londoner Bevölkerung. Aufgrund der Judenverfolgungen in Russland zogen in den 1880er-Jahren zudem viele osteuropäische Juden hierher. Ende des 19. Jahrhunderts lebten etwa 140.000 Juden in London, was einem Bevölkerungsanteil von gut 3 % entsprach."
                                   ],
                                   "title": "Migration"
                            },
                            "en": {
                                   "content": [
                                          "London had already become a cosmopolitan city by the early 19th century, whose economic upturn booming trade attracted migrants from the surrounding countryside, as well as all over England, the Empire and from across Europe. In the wake of the famines from 1845 to 1849, numerous Roman Catholic Irish migrants moved to the city, soon accounting for 20 percent of its population, almost all of whom lived in the overcrowded slums and were also discriminated against because of their religion. Economic hardship and political persecution resulted in many people fleeing to London from the German states and France, but also from Italy, Spain, Poland and elsewhere. Around 1850, about 1 percent of Londoners were born abroad, fifty years later the portion had risen to about 3 percent.",
                                          "The number of Jews rose steadily throughout the 19th century. Many worked in the banking sector, in the wholesale or retail trade, or as textile merchants. In general they were considerably better off than the average London resident. In the 1880s many Eastern European Jews fled to London to escape the pogroms in Russia. By the end of the 19th century, around 140,000 Jews lived in the city, constituting about 3 percent of the population."
                                   ],
                                   "title": "Migration"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Der Badebetrieb ist für das böhmische (aber nahezu ausschließlich deutschsprachige) Karlsbad bereits seit dem Mittelalter bezeugt. Der Kurbetrieb wurde vor allem 1711 und 1712 durch die Besuche des russischen Zaren Peter der Große gefördert.1819 wurden auf Betreiben des österreichischen Außenministers Clemens von Metternich auf einer Konferenz die so genannten Karlsbader Beschlüsse gefasst, in denen sich die Staaten des Deutschen Bundesauf eine strenge Pressezensur und andere Maßnahmen gegen die Demokratiebestrebungen festlegten.",
                                          "Im 19. Jahrhundert nahm der Kurbetrieb im nun – wie ganz Böhmen – zu Österreich gehörenden Karlsbad einen starken Aufschwung. Neben vielen anderen bedeutenden Persönlichkeiten besuchten etwa Wolfgang Amadeus Mozart, Ludwig van Beethoven, Johann Wolfang von Goethe, Kaiser Franz Joseph I., Nicolò Paganini und Frédéric Chopin das Bad. 1865 kamen rund 11.000 Besucher hierher, was etwa der Zahl für das belgische Spa entspricht, aber noch weit hinter Vichy (20.000), Wiesbaden (30.000) oder Baden-Baden (48.000) zurückblieb. Erst Ende des 19. Jahrhunderts war Karlsbad nach Wiesbaden und Baden-Baden das bedeutendste Kurbad Europas. Das Gros der Gäste kam aus dem Deutschen Reich, der Österreich-Ungarischen Monarchie und aus Russland, diese machten in den 1870er-Jahren zusammen etwa 90 % der Besucher aus. Karlsbad war somit weit weniger international als Baden-Baden, und es gab auch noch keine großen Hotels. Entscheidend für den Aufschwung des Badebetriebs wurde der Anschluss an das europäische Eisenbahnnetz. 1870 wurde der Betrieb auf der Strecke Karlsbad–Eger (Cheb) aufgenommen, kurz darauf folgte die Strecke nach Prag. 1886 konnte das neue Kurhaus eröffnet werden. Zum wirtschaftlichen Aufschwung trug auch die 1857 gegründete Glasfabrik Ludwig Moser & Söhne bei, die sehr hochwertige Produkte herstellte.",
                                          "1869 zählte die Stadt gut 14.000, 1880 bereits über 22.000 Einwohner. Die Bevölkerung war zu nahezu 100 % katholisch, jedoch gab es seit 1856 auch eine evangelische und seit 1877 eine anglikanische Kirche für die Kurgäste. Seit 1824 wurde auch den Juden der Aufenthalt in Karlsbad gestattet, jedoch nur während der Kursaison und nur an drei Tagen pro Woche, zudem ausschließlich als ambulante Hausierer, die keine Verkaufsstände errichten durften. Auf Druck der einheimischen Händler lehnte der Magistrat immer wieder Anträge ab, die den Juden längere Aufenthalte ermöglichen sollten. Erst als Kaiser Franz II. bei seinem Amtsantritt 1848 der Stadt untersagte, eigene Judenverordnungen zu erlassen, besserte sich die Lage der Juden ein wenig. 1853–1855 wurden sie jedoch erneut vertrieben. 1868 lebten immerhin rund 100 jüdische Familien in Karlsbad (wogegen die Zahl der Protestanten nur 50 betrug). 1869 gestattete das k.u. k. Kultusministerium schließlich den Bau einer Synagoge, die 1877 eingeweiht wurde."
                                   ],
                                   "title": "Karlsbad – der aufstrebende Kurort (Kuraufenthalte 1874–1876)"
                            },
                            "en": {
                                   "content": [
                                          "There is evidence of people attending the mineral baths in the Bohemian (although almost completely German-speaking) town of Carlsbad from the Middle Ages onwards. The popularity of the baths was particularly boosted by the visits of the Russian Czar Peter the Great in 1711 and 1712. At the instigation of the foreign minister Clemens von Metternich, a conference was held in the town in 1819 at which the states of the German Confederation resolved to enforce strict press censorship and other reactionary measures to quash the democratic movement that came to be known as the Carlsbad Decrees.",
                                          "In the 19th century, the spa resort in Carlsbad, which like all of Bohemia now belonged to Austria, experienced a boom. Over the centuries, many great luminaries visited the spa, including Wolfgang Amadeus Mozart, Ludwig van Beethoven, Johann Wolfgang von Goethe, Emperor Franz Joseph I, Nicolò Paganini, and Frédéric Chopin. In 1865, the resort attracted around 11,000 visitors, which was about the same as the numbers visiting the Belgian town of Spa but was considerably behind Vichy (20,000), Wiesbaden (30,000), and Baden-Baden (48,000). It was only towards the end of the 19th century that Carlsbad emerged as the third most important spa resort in Europe after Wiesbaden and Baden-Baden. The majority of visitors came from the German Empire, the Austro-Hungarian territories, and Russia, together making up about 90 percent of guests in the 1870s. Carlsbad was thus much less international than Baden-Baden and did not yet have any large hotels. Decisive for the boom was the town’s connection to the European rail network. In 1870, the railway line Carlsbad–Eger (Cheb) was opened, followed shortly afterwards by a connection to Prague. A new spa house opened in 1886. The glass factory Ludwig Moser & Söhne founded in 1857 with its high-quality products also contributed to the economic upturn.",
                                          "In 1869, the town had 14,000 inhabitants, by 1880 over 22,000. The population was almost 100 percent Roman Catholic, but a Protestant church was opened in 1856 and an Anglican church in 1877 for spa guests. Jews had been permitted to visit Carlsbad since 1824, but only during the official season and for a maximum of three days a week; moreover, while Jewish peddlers were permitted in the town, they were not allowed to set up stalls. Under pressure from local merchants, the town magistracy continually rejected applications to extend the length of time that Jews could reside in the town. The situation only improved somewhat on the appointment of Emperor Franz II in 1848 who forbade the town from issuing its own decrees concerning the Jewish populace. They were, nonetheless, expelled again from 1853 to 1855, but by 1868, about 100 Jewish families had settled in Carlsbad (in comparison to just 50 persons of the Protestant faith). In 1869, the Imperial and Royal Austro-Hungarian Ministry of Culture authorized the construction of a synagogue, which opened in 1877."
                                   ],
                                   "title": "Carlsbad – An Aspiring Spa Town (Visits to the Baths 1874–1876)"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Auf Anraten seines in Manchester wohnenden Arztes Eduard Gumpert und mit finanzieller Unterstützung durch Friedrich Engels reiste Karl Marx zusammen mit seiner Tochter Eleanor 1874 nach Karlsbad, wo er sich als „Charles Marx, Privatier, London“ tarnte. Eleanor hatte sich 1872 heimlich mit dem exilierten Kommunarden und Journalisten Prosper-Olivier Lissagaray verlobt, jedoch setzte ihre Familie ein Ende dieser Beziehung durch, und der Kuraufenthalt diente wohl auch dazu, Eleanor von ihrem Kummer abzulenken. Seit seiner Ankunft stand Karl Marx unter polizeilicher Beobachtung. Auch das absolute Alkoholverbot, das ihm sein Arzt auferlegt hatte, machte ihm zu schaffen.",
                                          "Im Jahr darauf suchte Karl Marx erneut den böhmischen Kurort auf, diesmal ohne seine Tochter, und, um nicht die für Privatiers geltende doppelte Kurtaxe zahlen zu müssen, nun als „Phil. Dr. Charles Marx“. Ein drittes Mal reiste er im August 1876 – wieder in Begleitung Eleanors – nach Karlsbad. Seiner chronisch angeschlagenen Gesundheit taten die Kuraufenthalte dort offensichtlich sehr gut."
                                   ],
                                   "title": "Karl Marx in Karlsbad"
                            },
                            "en": {
                                   "content": [
                                          "On the advice of his doctor in Manchester, Eduard Gumpert, and with the financial support of Friedrich Engels, Karl Marx and his daughter Eleanor travelled in 1874 to Carlsbad, where he assumed the fictitious identity ‘Charles Marx, privatier [gentleman of private means], London’. In 1872 Eleanor had secretly become engaged to the exiled Communard and journalist Prosper-Olivier Lissagaray. Her family, however, forced her to end the relationship and the trip to the spa was partly intended to distract Eleanor from her heartbreak. As soon as he arrived, Karl Marx was put under police observation. He found it difficult to adhere to the complete alcohol ban that his doctor had ordered, too.",
                                          "Karl Marx revisited the Bohemian spa resort a year later, without his daughter this time and signing himself in as ‘Phil. Dr. Charles Marx’ in order to avoid the double spa tax levied on gentlemen of independent means. He returned to Carlsbad for a third time in August 1876, again accompanied by Eleanor. His chronic health problems were evidently relieved by his time at the baths."
                                   ],
                                   "title": "Karl Marx in Carlsbad"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Fürst Karl III. von Monaco erteilte 1856 die Erlaubnis für ein Spielcasino. 1863 wurde dieses – zunächst als sehr bescheidenes Bauwerk –auf dem bis dahin unbebauten, mit Oliven-, Orangen- und Zitronenhainen genutzten Felsplateau nordöstlich der Stadt errichtet.",
                                          "1863 gründete Karl III. die „Société des Bains de Mer“ (SBM) und übertrug dem erfahrenen Unternehmer François Blanc, der zuvor u. a. das Casino in Bad Homburg geführt und den Ausbau des hessischen Kurorts vorangetrieben hatte, für fünfzig Jahre das Monopol für das Betreiben eines Spielcasinos im Fürstentum. 1866 gestattete der Fürst die Anlage eines neuen Stadtviertels auf dem Plateau, das seither zu seinen Ehren den Namen Monte-Carlo trug. Hier sollten ringsum das 1865 vollendete monumentale neue Casino Prachtbauten entstehen, die den Vergleich mit Paris nicht zu scheuen brauchten. 1864 führte Blanc das von ihm gemeinsam mit seinem Bruder für Bad Homburg weiterentwickelte Roulettespiel ein. Im selben Jahr eröffnete die SBM das Hôtel de Paris und 1868 das Café du Divan (ab 1881 Café de Paris). Hinzu kamen prunkvolle Villen und Gartenanlagen.",
                                          "Blanc bezahlte renommierte Journalisten, die den Ruf Monte-Carlos in die Welt hinaustragen sollten. Der Erfolg blieb nicht aus: Rasch entwickelte sich der Ort zum Anziehungspunkt für zahlreiche europäische Berühmtheiten, darunter den künftigen britischen König Eduard VII., den Schriftsteller Alexandre Dumas und den Komponisten Jacques Offenbach. Der Spielbankbetrieb und Grundstücksspekulationen verhalfen dem Fürsten und der Familie Blanc zu enormem Vermögen. Karl III. schaffte daraufhin alle Steuern in Monaco ab.",
                                          "Die Hauptstadt Monaco war seit 1863 dank der Eröffnung der Bahnstrecke Marseille–Ventimiglia über Lyon mit Paris verbunden. Um dem wohlhabenden Pariser Publikum auch eine direkte Verbindung nach Monte-Carlo zu ermöglichen, finanzierten François Blanc und seine Frau Marie den Bau des dortigen 1869 eröffneten Bahnhofs. Nachdem Blanc 1877 gestorben war, führte seine Witwe („Madame Monte-Carlo“) das Unternehmen, nach ihrem Tod der Sohn Camille Blanc. Marie Blanc beauftragte Charles Garnier, den Architekten der Pariser Oper, mit dem Bau der Opéra de Monte-Carlo, die 1879 mit einer Aufführung Sarah Bernardts eröffnet wurde. 1878–1880 wurde das Casino erweitert und umgebaut. Dieses erfreute sich nach dem 1872 von Bismarck angeordneten Spielbankverbot in ganz Deutschland und der Schließung des Casinos im schweizerischen Saxon-les-Bains 1878 für drei Jahrzehnte einer Monopolostellung für ganz Europa. So war in weniger als zwanzig Jahren aus einem unbebauten Felsplateau ein Luxusdomizil von Weltruf entstanden, das am Vorabend des Ersten Weltkriegs 9.600 (fast ausschließlich katholische) Einwohner zählen und eine höhere Bevölkerungsdichte als London aufweisen sollte."
                                   ],
                                   "title": "Monte-Carlo – Luxusstadt aus dem Nichts (1882)"
                            },
                            "en": {
                                   "content": [
                                          "Prince Charles III of Monaco issued the first concession for a casino in 1856. In 1863, a modest casino building was erected on an undeveloped rocky plateau, previously planted with olive, orange, and lemon groves, to the northeast of the city.",
                                          "In 1863, Charles III founded the Société des Bains de Mer (SBM) and granted the exclusive rights to operate a casino in the principality for a period of fifty years to the experienced entrepreneur François Blanc, who had previously managed the casino in Bad Homburg and had been instrumental in the expansion of the German spa resort. In 1866, the prince gave permission for a new quartier to be established on the escarpment that was named Monte-Carlo in his honour. The monumental new casino built in 1865 was to be surrounded by magnificent buildings that could easily rival those of Paris. In 1864, Blanc introduced a new kind of roulette that he and his brother had developed for Bad Homburg. In the same year, the SBM opened the Hôtel de Paris and, in 1868, the Café du Divan (renamed Café de Paris in 1881). They were further complemented by splendid villas and gardens.",
                                          "Blanc paid renowned journalists to promote Monte Carlo’s reputation worldwide. Success was not long in coming: the town rapidly developed into an attractive meeting place for many of Europe’s luminaries, including the future King Edward VII of Great Britain, the writer Alexandre Dumas, and the composer Jacques Offenbach. The prince and the Blanc family amassed a great fortune from the operation of the casino and property speculation. Charles III subsequently abolished all taxes in Monaco.",
                                          "The capital city of Monaco had been connected to Paris via Lyon since 1863 through the opening of the Marseille–Ventimiglia railway line. To provide a direct route to Monte Carlo for wealthy Parisians, François Blanc and his wife Marie financed the construction of the city’s train station which opened in 1869. When Blanc died in 1877, his wife (‘Madame Monte-Carlo’) continued to run the business, succeeded on her death by her son Camille Blanc. Marie Blanc commissioned Charles Garnier, the architect of the Paris opera house, to build the Opéra de Monte-Carlo, which opened its doors in 1879 with a performance by Sarah Bernardt. The casino was extended and refurbished from 1878 to 1880. After Bismarck prohibited all casinos in Germany in 1872 and the Swiss casino in Saxon-les-Bains closed in 1878, it enjoyed a monopoly in Europe for three decades. In less than twenty years, an undeveloped rocky plateau evolved into a lavish residential town of global standing, which on the eve of World War One had 9,600 (almost exclusively Roman Catholic) inhabitants and a higher population density than London."
                                   ],
                                   "title": "Monte Carlo – A Luxurious City Built from Nothing (1882)"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Auf der Rückreise von Algier gelangte Karl Marx über Marseille und Nizza nach Monte-Carlo. Hier traf er am 7. Mai 1882 ein und stieg im Hôtel de Russie ab. Er begab sich in ärztliche Behandlung und erhoffte sich von der Seeluft eine Linderung seiner Leiden. Am 3. Juni reiste er über Cannes zurück nach Argenteuil zur Familie seiner Tochter Jenny. Über die fürstliche Dynastie sowie das „öde Nest“ Monte-Carlo und sein mondänes Publikum äußerte er sich spöttisch."
                                   ],
                                   "title": "Karl Marx in Monte Carlo"
                            },
                            "en": {
                                   "content": [
                                          "On his return from Algiers, Karl Marx travelled to Monte Carlo via Marseille and Nice. He arrived in the city on 7 May 1882 and stayed at the Hôtel de Russie. He attended a doctor to undergo various medical treatments and hoped that the sea air would alleviate his ailments. On 3 June, he travelled to Argenteuil via Cannes to visit his daughter Jenny and family. He mocked the princely dynasty with derisive comments about the ‘dreary nest’ of Monte Carlo and its worldly public."
                                   ],
                                   "title": "Karl Marx in Monte Carlo"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Das nur wenige Kilometer seineabwärts von Paris gelegene Argenteuil, um 1800 noch ein Winzerstädtchen mit rund 5.000 Einwohnern, erlebte während des 19. Jahrhunderts einen rasanten Aufschwung, da sich hier seit dem Bau der Seinebrücke 1832 mehrere Manufakturen ansiedelten. Zudem besaß es die größten Gipsvorkommen Europas, die wesentlich zur Umgestaltung von Paris unter Georges-Eugène Haussmann beitrugen. Argenteuil war wegen seiner lieblichen Landschaft ein sehr beliebtes Ausflugsziel für das Pariser Bürgertum, vor allem seit es ab 1851 bequem mit der Eisenbahn zu erreichen war. Seither ließen sich immer mehr Industriebetriebe hier nieder. Das Stahlwerk Joly lieferte u. a. das Material für den Bau des Eiffelturms, des Bahnhofs Saint-Lazare und der Hallen von Paris. Berühmt war die Stadt, die 1881 bereits knapp 12.000 Einwohner zählte, auch für ihren Spargelanbau. Nahezu alle bedeutenden Impressionisten haben sie im Bilde festgehalten. Claude Monet lebte hier von 1871 bis 1878. Auch Alfred Sisley, Édouard Manet, Camille Pissarro, Vincent van Gogh und Gustave Caillebotte schätzten ihre schönen Panoramen und Weinstuben. Georges Braque wurde hier 1882 geboren.",
                                          "Mit Trier verbindet Argenteuil die Tatsache, dass man sich auch dort im Besitz der Tunica Christi, des Heiligen Rocks, glaubt. Dieser soll durch Kaiserin Helena dorthin gebracht worden sein, wurde im Mittelalter verehrt und zog im 19. Jahrhundert (nach Beschädigungen durch die Hugenotten und während der Französischen Revolution) zahlreiche Pilger an; die letzte Zeigung fand 1984 statt."
                                   ],
                                   "title": "Argenteuil – Industriestadt und Ausflugsziel (Familienbesuche 1881 und 1882)"
                            },
                            "en": {
                                   "content": [
                                          "Situated just a few kilometres down the River Seine from Paris, Argenteuil was a small viticultural town in 1800 with around 5,000 inhabitants. It experienced rapid growth in the 19th century when many factories set up there after the construction of the bridge over the Seine in 1832. It also had the largest deposits of gypsum in Europe – a material that was essential to the redesign of Paris under Georges-Eugène Haussmann. Argenteuil was a very popular destination for well-off Parisians because of its picturesque landscape, especially once it could be easily reached by train from 1851. An increasing number of industrial manufacturers set up there at the same time. The Joly ironworks, for instance, supplied the material for the construction of the Eiffel Tower, the Saint-Lazare train station and Les Halles de Paris. The town was also famed for its asparagus and by 1881 its population had grown to almost 12,000. Argenteuil was immortalized by nearly all of the major Impressionists. Claude Monet lived there from 1871 to 1878, Alfred Sisley, Édouard Manet, Camille Pissarro, Vincent van Gogh, and Gustave Caillebotte admired its beautiful vistas and wine taverns, and Georges Braque was born there in 1882.",
                                          "Argenteuil is also linked to Trier by the fact that it, too, claims to be in possession of the Tunica Christi, the Sacred Robe of Christ. Allegedly brought there by Empress Helena, it was worshipped in the Middle Ages and attracted numerous pilgrims in the 19th century (after suffering damage at the hands of the Huguenots and during the French Revolution); it last went on display in 1984."
                                   ],
                                   "title": "Argenteuil – Industrial Town and Holiday Destination\n(Family Visits 1881 and 1882)"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "1872 hatte Marx' Tochter Jenny den Journalisten und Kommunarden Charles Longuet geheiratet. Das Paar siedelte 1881 mit seinen drei Söhnen Jean (John), Henri und Edgar von London nach Argenteuil um, wo im folgenden Jahr der vierte Sohn Marcel geboren wurde. Daraufhin statteten Karl und Jenny Marx sowie Helene Demuth der Familie im Juni einen Besuch ab – es wurde Jennys letzte Reise vor ihrem Tod. Eine Woche später brachte Jenny(chen) eine – ebenfalls Jenny genannte – Tochter zur Welt. Sie selbst starb jedoch nach langer Krankheit 1883 zwei Monate vor ihrem Vater im Alter von 38 Jahren an Blasenkrebs. Sie ist die Ahnin aller noch lebender Nachkommen von Karl Marx.",
                                          "1882 besuchte Karl Marx sowohl auf dem Hin- als auch auf dem Rückweg seiner Mittelmeerreise Jennychen und ihre Familie in Argenteuil. Die beiden anderen Töchter Laura und Eleanor hielten sich damals ebenfalls dort auf. Dies war Karl Marx' letzte Reise."
                                   ],
                                   "title": "Karl Marx in Argenteuil"
                            },
                            "en": {
                                   "content": [
                                          "In 1872, Marx’s daughter Jenny married the journalist and Communard Charles Longuet. The couple and their three sons Jean (John), Henri, and Edgar moved from London to Argenteuil in 1881, where their fourth son Marcel was born a year later. Karl and Jenny Marx together with Helene Demuth visited the family in June – it was to be Jenny’s last journey before her death. One week later, Jenny(chen) gave birth to a daughter whom she also called Jenny. After a long illness, she died at the age of 38 from bladder cancer two months before her father in 1883. All living descendants of Karl Marx today can be traced back to Jenny Marx.",
                                          "In 1882, Karl Marx visited Jennychen and her family in Argenteuil both on his way to and back from the Mediterranean. His other two daughters, Laura and Eleanor, were also staying there at the time. It was the last time that Karl Marx travelled before his death."
                                   ],
                                   "title": "Karl Marx in Argenteuil"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "1830 hatte Frankreich das bis dahin zum Osmanischen Reich gehörige Algerien erobert, das seit 1848 offiziell Teil Frankreichs mit Algier als Hauptstadt des gleichnamigen Departements war. Zur Zeit der Eroberung gab es dort etwa 12.000 Häuser, rund hundert Moscheen und zehn Synagogen. Die Oberstadt war eng bebaut, ringsum lagen Villen und Gärten. Die einheimische Bevölkerung wurde großenteils vertrieben, die Verbliebenen waren gezwungen, ihre Arbeitskraft den Kolonialherren zu sehr niedrigen Löhnen zur Verfügung zu stellen. Seit der Jahrhundertmitte kam es zu einer (von Frankreich geförderten) massiven Zuwanderung aus Europa – auch aus dem Trierer Raum. Der Besitz der Einheimischen wurde enteignet und den europäischen Bedürfnissen entsprechend umgebaut. Die arabische Sprache verschwand immer mehr aus dem öffentlichen Leben. Auch die Bildungsmöglichkeiten für die Muslime waren äußerst begrenzt. Noch Ende des 19. Jahrhunderts konnten unter ihnen nur gut 5 % lesen und schreiben. Um in ihrer Muttersprache studieren zu können, mussten sie ins Ausland, etwa nach Tunis oder Kairo, gehen.",
                                          "Vor allem im Osten der Stadt, wo sich auch der Hafen befindet, wurde viel investiert (Rathaus, Gouverneurspalast, Gerichtshof, Theater, Postamt), wofür man die traditionelle Bebauung teilweise zur Anlage breiter Straßen abriss. Seit 1840 dehnte sich die Stadt über die osmanischen Mauern hinaus aus, die Kolonisten zog es nun verstärkt in die Vorstädte. Große Teile Algiers erhielten ein europäisches Gesicht nach Pariser Vorbild, wogegen die Altstadt, in der die arabische Bevölkerung lebte, immer mehr verfiel.",
                                          "Nach der Annexion Elsass-Lothringens durch das Deutsche Reich 1871 flohen viele Menschen aus diesen Gebieten nach Algerien. Gegen Ende des 19. Jahrhunderts zählte Algier etwa 100.000 Einwohner, von denen die Mehrheit europäische Wurzeln hatte. Unter den Zuwanderern stellten die Franzosen gut die Hälfte, die Spanier ein knappes Drittel. Rund 10 % der Stadtbevölkerung waren Juden."
                                   ],
                                   "title": "Algier – eine französische Kolonialstadt (1883)"
                            },
                            "en": {
                                   "content": [
                                          "In 1830, France invaded Algeria, which had belonged to the Ottoman Empire up until then. It was officially made a territory of France in 1848, forming a department, with Algiers as its capital city. At the time of the conquest, the city consisted of about 12,000 houses, around 100 mosques and ten synagogues. The upper town was densely built up and surrounded by villas and gardens. The native population was largely displaced and those who remained supplied the workforce for the colonial elite at very low wages. From the mid-century, the country experienced a huge influx of migrants (encouraged by France) from all over Europe, including the Trier region. The property of the native population was expropriated and modified to meet European expectations. Arabic was spoken less and less, eventually disappearing from public life. Access to education was extremely restricted for Muslims. At the end of the 19th century, only 5 percent of the Muslim populace could read and write. In order to study in their native language they had to go abroad, to Tunisia or Cairo, for example.",
                                          "Considerable investment went into developing the city especially to the east where the port was situated (e.g., the town hall, Governor’s Palace, courthouse, theatre, and post office). In the course of the development, traditional buildings were torn down, partly to make way for wider streets. From 1840, the city expanded beyond the Ottoman walls, as the colonists began to populate the outlying towns. Large parts of Algiers were given a European facelift, styled after Paris, while the old town in which the Arab populace lived became increasingly derelict.",
                                          "After Alsace-Lorraine was annexed by the German Empire in 1871, many people from the region fled to Algeria. At the close of the 19th century, Algiers had around 100,000 inhabitants, the majority of whom had European roots. At least half of the immigrants were French and almost a third Spanish. About 10 percent of the urban population was Jewish."
                                   ],
                                   "title": "Algiers – A French Colonial Town (1883)"
                            }
                     },
                     {
                            "de": {
                                   "content": [
                                          "Vom milden, mediterranen Frühlingsklima Algiers erhoffte sich Karl Marx Linderung für seine durch Rippenfell-, Lungenentzündung und Bronchitis ausgelösten Leiden. Kontakte bestanden zu dem Richter Albert Fermé, der ein Bekannter seiner Schwiegersöhne Paul Lafargue und Charles Longuet war. Am 20. Februar 1882 traf Marx in Algier ein – wo bis 1862 übrigens seine Tante Babette gelebt hatte. Zwei Tage später bezog er ein Zimmer im Hôtel Pension Victoria außerhalb der Stadt. Seine Korrespondenz aus Algier mit Friedrich Engels sowie seinen Töchtern dreht sich fast ausschließlich ums Wetter (das für die Jahreszeit völlig ungewöhnlich unbeständig war) und seine verschiedenen Therapien (die nur wenig Linderung brachten). Er schreibt jedoch auch über die „herrliche Lage“ der Stadt und die „Arroganz“ der Kolonialherren. Am 2. Mai fuhr er zurück nach Marseille."
                                   ],
                                   "title": "Karl Marx in Algier"
                            },
                            "en": {
                                   "content": [
                                          "Karl Marx hoped that Algiers’ mild, Mediterranean spring climate would alleviate the pain he suffered from pleurisy and bronchitis. It was also where he met the judge Albert Fermé, who was an acquaintance of his sons-in-law Paul Lafargue and Charles Longuet. Marx arrived in Algiers on 20 February 1882 – the hometown of his Aunt Babette until 1862. Two days later, he took up lodgings at the Hôtel Pension Victoria outside of the city. The letters he wrote in Algiers to Friedrich Engels and his daughters are almost exclusively about the weather (which was unusually changeable for the time of year) and his different treatments (which brought little relief). He also writes about the ‘magnificent location’ of the city and the ‘arrogance’ of the colonial rulers. On 2 May, he returned to Marseille."
                                   ],
                                   "title": "Karl Marx in Algiers"
                            },
                            "has_english": true
                     }
              ],
              "name": "London"
       }
]